In [61]:
#1. Numpy:
#imporing numpy lib as np
import numpy as np

In [62]:
"Using NumPy create random vector of size 15 having only Integers in the range 1-20."
"used rand int to create random array"
rints = np.random.randint(1,20,15)
#rints = rng.integers(low=1, high=20, size=15)

In [63]:
"Print randomly generated array."
print(rints)

[ 7 16 12 15 10 16  4  8 17  8  7 13 19  2 18]


In [64]:
"1. Reshape the array to 3 by 5"
#using reshape method reshaping the array
matrix=rints.reshape((3,5))

In [65]:
#2. Print array shape.
"Print 3x5 array shape."
print(matrix)

[[ 7 16 12 15 10]
 [16  4  8 17  8]
 [ 7 13 19  2 18]]


In [66]:
#store max values items indexs in each row
max_ind = np.argmax(matrix, axis=1)
print(max_ind)

[1 3 2]


In [67]:
#list of rows indexs in matrix
row_index = np.arange(matrix.shape[0])
print(row_index)

[0 1 2]


In [69]:
#store moth inan array
multi_ind = np.array([row_index, max_ind])
print(multi_ind)

[[0 1 2]
 [1 3 2]]


In [70]:
#with the help of ravel_multi_index find the linear index positions of max elements
linear_ind = np.ravel_multi_index(multi_ind, matrix.shape)
print(linear_ind)

[ 1  8 12]


In [71]:
#with help of reshape(-1) now we access linear form of array
matrix.reshape((-1))[linear_ind] = 0
print(matrix)

[[ 7  0 12 15 10]
 [16  4  8  0  8]
 [ 7 13  0  2 18]]


In [72]:
#4. Extract a diagonal from the array and save it as .npy file format.
"extracting diagonal"
"Extract a diagonal from the array"
diagonal=np.diag(matrix)

In [73]:
"save it as .npy file format."
np.save("array.npy", diagonal)

In [74]:
"loading it back"
print(np.load("array.npy"))

[7 4 0]
